name: Test Call Helm Charts Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to pass to helm-charts workflow"
        required: true
        default: "1.2.3"

jobs:
  call-external:
    uses: igorsilva-dev/helm-charts/.github/workflows/release-app.yaml@main
    with:
      application: flask-app
      version: ${{ github.event.inputs.version }}
